services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sql-server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "TuContrase√±a123*"
    ports:
      - "1433:1433"
    volumes:
      - sql-server:/var/opt/mssql

volumes:
  sql-server:
